debug: false

#redis 集群模式
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  redis:
    cluster:
      nodes: 192.168.0.107:6379,192.168.0.107:6380,192.168.0.107:6381
      max-redirects: 5
      password: cornel00147258
      timeout: 5


jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      expireAfterWriteInMillis: 60000


caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=10s,recordStats
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
      redis:
        timeToLive: 15m
    near-city-info-cache:
      caffeine:
        spec: maximumSize=1000,expireAfterWrite=5h,recordStats
    fh-py-flight-list:
      caffeine:
        spec: maximumSize=5000,expireAfterWrite=5m,recordStats
    dist-hotel-base-info:
      caffeine:
        spec: maximumSize=50000,expireAfterWrite=1m,recordStats
    hotel-can-sell-suppliers:
      caffeine:
        spec: maximumSize=100000,expireAfterWrite=5s,recordStats
    hotel-room-type-en-name-map:
      caffeine:
        spec: maximumSize=200000,expireAfterWrite=6h,recordStats
    hotel-comment-tag:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=6h,recordStats
    fh-py-res-config:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=30m,recordStats
    fh-online-hotel:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=5m,recordStats
    fh-hotel-simple-base-info:
      caffeine:
        spec: maximumSize=100000,expireAfterWrite=30m,recordStats
        cacheNullValues: false

we-chat:
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={appId}&secret={appSecret}&js_code={jscode}&grant_type=authorization_code
  appId: wx5bde5e1ca69bd7f6
  appSecret: 80dc07ef341d0c59314d935378075068
we-chat-driver:
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={appId}&secret={appSecret}&js_code={jscode}&grant_type=authorization_code
  appId: wxbcb8b37ff9f2ce18
  appSecret: 0ba267b4ad3f37bd0e591d557e5144aa


ali-config:
  accessKeyId: LTAI4FjjDZfU5McHXiDEH2Uk
  accessSecret: 1C6KdK5kBZurVkFTSqp8wPE2mvJpBB
  loginValidcodeId: SMS_176539582

datasources:
  dm-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://192.168.0.107:5432/cornel_product'
    username: cornel_prd
    password: a9e43160-7d34-4a9d-8120-f605b111ce59
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000
xxl:
  job:
    admin:
      addresses: http://182.92.1.233:9528
    accessToken: ''
    executor:
      appname: cornel
      ip: 182.92.1.233
      port: 9999
      logpath: '/home/www/cornel_web/logs/'
      logretentiondays: 10
baidu:
  ak: 1EBYcarYLWPnnpUbrX4SUxQwtLSjgvF0
service:
  mobileList: 18904015597
banner:
  download: https://demeteria.com/banner/download.json?key=1.png,https://demeteria.com/banner/download.json?key=2.png
  purchaseBanner: https://beta.demeteria.com/banner/download.json?key=3.png,https://beta.demeteria.com/banner/download.json?key=4.png
upload:
  location: :
  downloadHost: https://demeteria.com
car-config:
  carlicetype: 本人,他人,公司